version: "3.7"

services:
  jaeger:
    container_name: "jaeger"
    image: jaegertracing/all-in-one:1.17
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "5778:5778"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.${BASE_DOMAIN}`)"
      - "traefik.http.routers.jaeger.entrypoints=websecure"
      - "traefik.http.routers.jaeger.tls.certresolver=bizapps"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
      - "traefik.http.services.jaeger.loadbalancer.passhostheader=true"
    env_file:
      - .env